repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-docstring-first
    -   id: check-toml
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
    -   id: mixed-line-ending
        args: [--fix=lf]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.4
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format

-   repo: local
    hooks:
    -   id: check mypy
        name: mypy
        language: system
        types: [python]
        entry: bash -c "cd billing_api/src && mypy --follow-imports=skip ."
