repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-docstring-first
    -   id: check-toml
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch

-   repo: local
    hooks:
    -   id: check ruff
        name: ruff
        language: system
        types: [python]
        entry: ruff
        args: [check, --output-format=full]
    -   id: check mypy
        name: mypy
        language: system
        types: [python]
        entry: mypy
        args: [--follow-imports=skip]
