target-version = "py311"
line-length = 120
fix = true

lint.ignore = [
    # AmbiguousUnicodeCharacterString
    "RUF001",
    # ambiguous-unicode-character-docstring
    "RUF002",
    # ambiguous-unicode-character-comment
    "RUF003",
    # Avoid specifying long messages outside the exception class
    "TRY003",
    # function-call-in-default-argument
    "B008",
]

lint.select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # flake8-print
    "T20",
    # blind exceprt
    "BLE",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E",
    # pycodestyle
    "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]

[lint.mccabe]
max-complexity = 45
