"""add_is_default_card

Revision ID: f2214574000e
Revises: d753678ac137
Create Date: 2024-11-23 07:53:48.613118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2214574000e'
down_revision: Union[str, None] = 'd753678ac137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercardsstripes', sa.Column('is_default', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercardsstripes', 'is_default')
    # ### end Alembic commands ###
