"""add_user_cards

Revision ID: d753678ac137
Revises: 92e71bbd1b27
Create Date: 2024-11-22 19:31:42.958585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd753678ac137'
down_revision: Union[str, None] = '92e71bbd1b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('INIT', 'SUCCESS', 'FAIL', name='status_cards_enum').create(op.get_bind())
    op.create_table('usercardsstripes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_user_id', sa.String(), nullable=False),
    sa.Column('token_card', sa.String(), nullable=True),
    sa.Column('status', postgresql.ENUM('INIT', 'SUCCESS', 'FAIL', name='status_cards_enum', create_type=False), nullable=False),
    sa.Column('last_numbers_card', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usercardsstripes')
    sa.Enum('INIT', 'SUCCESS', 'FAIL', name='status_cards_enum').drop(op.get_bind())
    # ### end Alembic commands ###
