"""add_is_archive_feild_to_SubscriptionPlan

Revision ID: 6c8b90e219a8
Revises: 66e2cb6f9f1e
Create Date: 2024-12-02 14:07:17.057138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8b90e219a8'
down_revision: Union[str, None] = '66e2cb6f9f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptionplans', sa.Column('is_archive', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptionplans', 'is_archive')
    # ### end Alembic commands ###
