"""add_archive_field_to_SubscriptionPlan

Revision ID: fd563f5cc6ff
Revises: 66e2cb6f9f1e
Create Date: 2024-12-01 16:28:33.102292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd563f5cc6ff'
down_revision: Union[str, None] = '66e2cb6f9f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptionplans', sa.Column('archive', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptionplans', 'archive')
    # ### end Alembic commands ###
