"""init

Revision ID: 2fc2ff787132
Revises: 
Create Date: 2024-11-18 15:23:18.139700

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '2fc2ff787132'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
