"""user_cards

Revision ID: 4255cd236516
Revises: 2fc2ff787132
Create Date: 2024-11-21 18:42:18.222734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4255cd236516'
down_revision: Union[str, None] = '2fc2ff787132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cards_stripe',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_user_id', sa.String(), nullable=False),
    sa.Column('token_card', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('INIT', 'SUCCESS', 'FAIL', name='status_cards_enum'), nullable=False),
    sa.Column('last_numbers_card', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cards_stripe')
    # ### end Alembic commands ###
